# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InCV4HyKNjYbbaqV9k0iLNpV3OToSoGY
"""

"""
Project 6: Student Placement Prediction
Model: Logistic Regression
Dataset: Campus Recruitment Dataset
Source: Kaggle - benroshan

Target Variable: status
"""

# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Set visualization style
sns.set_style("whitegrid")

# Create folder for saving images
IMG_DIR = "/content/Images"
os.makedirs(IMG_DIR, exist_ok=True)


# ============================================================
# 2. LOAD DATASET
# ============================================================

# Make sure Placement_Data_Full_Class.csv is uploaded to Colab
df = pd.read_csv("/content/Placement_Data_Full_Class.csv")

print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

print("\nFirst 5 rows:")
print(df.head())

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)


# ============================================================
# 3. CHECK MISSING VALUES
# ============================================================

print("\nMissing values:")
print(df.isnull().sum())

# Salary is missing for students who were not placed.
# This is expected in this dataset.
print("\nSalary missing values by placement status:")
print(df.groupby("status")["salary"].apply(lambda x: x.isnull().sum()))


# ============================================================
# 4. DATA CLEANING
# ============================================================

# Drop salary because it is only available after placement.
# Using it would cause data leakage.
#
# Drop sl_no because it is only a serial number and has no
# meaningful predictive value.

df_clean = df.drop(columns=["salary", "sl_no"])

print("\nDataset after dropping salary and sl_no:")
print(df_clean.head())

# Remove extra spaces from categorical columns
categorical_cols = [
    "gender",
    "workex",
    "hsc_s",
    "degree_t",
    "specialisation",
    "status"
]

for col in categorical_cols:
    df_clean[col] = df_clean[col].astype(str).str.strip()

# Check unique values
print("\nUnique values in categorical columns:")

for col in categorical_cols:
    print(f"\n{col}:")
    print(df_clean[col].unique())


# ============================================================
# 5. EXPLORATORY DATA ANALYSIS
# ============================================================

# ------------------------------------------------------------
# 5.1 Placement by Specialisation and Work Experience
# ------------------------------------------------------------

fig, ax = plt.subplots(1, 2, figsize=(12, 5))

sns.countplot(
    data=df_clean,
    x="specialisation",
    hue="status",
    ax=ax[0]
)

ax[0].set_title("Placement by Specialisation")
ax[0].set_xlabel("Specialisation")
ax[0].set_ylabel("Number of Students")

sns.countplot(
    data=df_clean,
    x="workex",
    hue="status",
    ax=ax[1]
)

ax[1].set_title("Placement by Work Experience")
ax[1].set_xlabel("Work Experience")
ax[1].set_ylabel("Number of Students")

plt.tight_layout()

plt.savefig(
    f"{IMG_DIR}/01_placement_by_spec_workex.png",
    dpi=110,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 5.2 Academic Score Distributions
# ------------------------------------------------------------

fig, ax = plt.subplots(1, 3, figsize=(15, 5))

score_columns = [
    "ssc_p",
    "hsc_p",
    "degree_p"
]

for i, col in enumerate(score_columns):

    sns.kdeplot(
        data=df_clean,
        x=col,
        hue="status",
        fill=True,
        common_norm=False,
        ax=ax[i]
    )

    ax[i].set_title(f"{col} Distribution by Placement Status")
    ax[i].set_xlabel(col)
    ax[i].set_ylabel("Density")

plt.tight_layout()

plt.savefig(
    f"{IMG_DIR}/02_score_distributions.png",
    dpi=110,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 5.3 Correlation Heatmap
# ------------------------------------------------------------

# Convert placement status into binary values
# Placed = 1
# Not Placed = 0

df_corr = df_clean.copy()

df_corr["status_bin"] = (
    df_corr["status"] == "Placed"
).astype(int)

score_columns = [
    "ssc_p",
    "hsc_p",
    "degree_p",
    "etest_p",
    "mba_p"
]

corr = df_corr[
    score_columns + ["status_bin"]
].corr()

plt.figure(figsize=(8, 6))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title(
    "Correlation Heatmap: Academic Scores vs Placement"
)

plt.tight_layout()

plt.savefig(
    f"{IMG_DIR}/03_correlation_heatmap.png",
    dpi=110,
    bbox_inches="tight"
)

plt.show()

print("\nCorrelation of academic scores with placement:")
print(
    corr["status_bin"]
    .sort_values(ascending=False)
)


# ------------------------------------------------------------
# 5.4 MBA Percentage vs Placement
# ------------------------------------------------------------

plt.figure(figsize=(7, 5))

sns.boxplot(
    data=df_clean,
    x="status",
    y="mba_p"
)

plt.title("MBA Percentage vs Placement Status")
plt.xlabel("Placement Status")
plt.ylabel("MBA Percentage")

plt.tight_layout()

plt.savefig(
    f"{IMG_DIR}/04_mba_p_vs_status.png",
    dpi=110,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 6. FEATURE ENGINEERING
# ============================================================

df_fe = df_clean.copy()

# Create average academic score
df_fe["academic_average"] = df_fe[
    ["ssc_p", "hsc_p", "degree_p"]
].mean(axis=1)

# Convert work experience into binary
# Yes = 1
# No = 0

df_fe["workex_flag"] = (
    df_fe["workex"] == "Yes"
).astype(int)

print("\nFeature engineered dataset:")
print(df_fe.head())


# ============================================================
# 7. ENCODE CATEGORICAL VARIABLES
# ============================================================

# One-hot encode categorical variables
# Drop first category to avoid dummy variable trap

cat_cols = [
    "gender",
    "hsc_s",
    "degree_t",
    "specialisation"
]

df_encoded = pd.get_dummies(
    df_fe,
    columns=cat_cols,
    drop_first=True
)

# Drop unnecessary columns
df_encoded = df_encoded.drop(
    columns=[
        "ssc_b",
        "hsc_b",
        "workex"
    ]
)

# Convert boolean columns to integers
bool_columns = df_encoded.select_dtypes(
    include="bool"
).columns

df_encoded[bool_columns] = (
    df_encoded[bool_columns]
    .astype(int)
)

print("\nEncoded dataset:")
print(df_encoded.head())


# ============================================================
# 8. ENCODE TARGET VARIABLE
# ============================================================

le = LabelEncoder()

df_encoded["status_encoded"] = le.fit_transform(
    df_encoded["status"]
)

print("\nTarget encoding:")
print(
    dict(
        zip(
            le.classes_,
            le.transform(le.classes_)
        )
    )
)


# ============================================================
# 9. DEFINE FEATURES AND TARGET
# ============================================================

X = df_encoded.drop(
    columns=[
        "status",
        "status_encoded"
    ]
)

y = df_encoded["status_encoded"]

print("\nFeature shape:", X.shape)
print("Target shape:", y.shape)


# ============================================================
# 10. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)


# ============================================================
# 11. FEATURE SCALING
# ============================================================

# Scaling is useful for Logistic Regression because
# features have different ranges.

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)


# ============================================================
# 12. BUILD LOGISTIC REGRESSION MODEL
# ============================================================

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Train model
model.fit(
    X_train_scaled,
    y_train
)

# Make predictions
y_pred = model.predict(
    X_test_scaled
)


# ============================================================
# 13. MODEL EVALUATION
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred
)

recall = recall_score(
    y_test,
    y_pred
)

f1 = f1_score(
    y_test,
    y_pred
)

print("\n" + "=" * 50)
print("MODEL PERFORMANCE")
print("=" * 50)

print(f"Accuracy:  {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall:    {recall:.3f}")
print(f"F1 Score:  {f1:.3f}")


# ============================================================
# 14. CLASSIFICATION REPORT
# ============================================================

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=le.classes_
    )
)


# ============================================================
# 15. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    y_pred
)

plt.figure(figsize=(6, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=le.classes_,
    yticklabels=le.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.tight_layout()

plt.savefig(
    f"{IMG_DIR}/05_confusion_matrix.png",
    dpi=110,
    bbox_inches="tight"
)

plt.show()


# ============================================================
# 16. FEATURE IMPORTANCE USING LOGISTIC REGRESSION
# ============================================================

coef_df = pd.DataFrame({
    "feature": X.columns,
    "coefficient": model.coef_[0]
})

# Sort by coefficient
coef_df = coef_df.sort_values(
    by="coefficient",
    ascending=False
)

print("\nFeature coefficients:")
print(
    coef_df.to_string(index=False)
)


# ============================================================
# 17. TOP FACTORS AFFECTING PLACEMENT
# ============================================================

print("\n" + "=" * 50)
print("TOP FACTORS AFFECTING PLACEMENT")
print("=" * 50)

print(
    "\nPositive coefficients indicate features that "
    "increase the model's predicted probability of placement."
)

print("\nTop positive factors:")

print(
    coef_df.head(10).to_string(index=False)
)

print("\nTop negative factors:")

print(
    coef_df.tail(10).sort_values(
        by="coefficient"
    ).to_string(index=False)
)


# ============================================================
# 18. PLACEMENT RATE ANALYSIS
# ============================================================

print("\n" + "=" * 50)
print("PLACEMENT RATE BY WORK EXPERIENCE")
print("=" * 50)

workex_placement = pd.crosstab(
    df_clean["workex"],
    df_clean["status"],
    normalize="index"
) * 100

print(
    workex_placement.round(2)
)


print("\n" + "=" * 50)
print("PLACEMENT RATE BY SPECIALISATION")
print("=" * 50)

specialisation_placement = pd.crosstab(
    df_clean["specialisation"],
    df_clean["status"],
    normalize="index"
) * 100

print(
    specialisation_placement.round(2)
)


# ============================================================
# 19. RECOMMENDATIONS
# ============================================================

print("\n" + "=" * 50)
print("PLACEMENT IMPROVEMENT RECOMMENDATIONS")
print("=" * 50)

print("""
1. Gain relevant work experience:
   Students with prior work experience may have better placement
   outcomes in this dataset.

2. Maintain strong academic performance:
   SSC, HSC, degree and MBA percentages can influence the model's
   placement predictions.

3. Choose specialisation carefully:
   Placement outcomes may differ between specialisations in this
   dataset.

4. Improve employability skills:
   Students should also focus on communication, aptitude,
   interview preparation and technical skills.

5. Build practical experience:
   Internships, projects and industry exposure can improve
   job readiness.

NOTE:
These recommendations are based on patterns in the dataset and
Logistic Regression coefficients. They do not prove causation.
Real-world placement decisions also depend on interviews,
skills, company requirements and market conditions.
""")


# ============================================================
# 20. DISPLAY SAVED IMAGE LOCATION
# ============================================================

print("\nAll graphs have been saved successfully in:")
print(IMG_DIR)